version: '3.3'
services:
  
  mongo_db:
    image: ${DBIMAGE} 
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    build: ./ui
    image: ${USERNAME}/ui:${BUILD}
    ports:
      - 9292:9292/tcp
    networks:
      - front_net
      - back_net

  post:
    build: ./post-py
    image: ${USERNAME}/post:${BUILD}
    networks:
      back_net:
        aliases:
          - reddit_post

  comment:
    build: ./comment
    image: ${USERNAME}/comment:${BUILD}
    networks:
      back_net:
        aliases:
          - reddit_comment

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    networks:
      - back_net
      - front_net

  node-exporter:
    image: prom/node-exporter:v0.15.0
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      back_net:
        aliases:
          - node-exporter

volumes:
  post_db:

networks:
  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
